### ISSUE TITLE
dependency injection and oops.js

### ISSUE THREAD

**Issue by millerthegorilla** [Cleod9/importjs#2]
Hi, I am making an animated vine, and I have two classes extending a class called climberbase using OOPS.extend.
One of the classes is called climber, which is the main vine, of which there is only one instance and the other class is called branch, of which there are many.
I have a function in the climberbase called _grow, which is called by the 

``` javascript
window.requestAnimationFrame(this._grow.bind(this))
```

In this '_grow' is a call to create a new branch.
Due to this a circular dependency occurs, and so I use 

``` javascript
this.inject(function() 
{
   branch = this.import('vine.branch');
});
```

However, when the new branch is created, it never enters the constructor of the branch, even though one is defined.  I am not certain why this might be, but I wonder if it might not be because of the dependency injection.  When I debug, OOPS returns an empty child (from line 37 of oops.js), even though the _constructor_ function is defined in the child class.
I don't know how to proceed,  can you help please? 
Many thanks.  (I'm loving importjs btw and oops is a great help too!)

**Comment by millerthegorilla** [comment]
btw, can you clarify for me the difference between

``` javascript
this.import
```

and 

``` javascript
ImportJS.unpack
```

I have tried to place ImportJS.unpack in the dependency inject function for late binding, but the browser console complains that the package cannot be found.  Many thanks.

**Comment by Cleod9** [comment]
I'm glad you like ImportJS!

I think I have an idea what your problem might be, but I think I need to see more of the code. Are you able to set up a [JSFiddle](http://jsfiddle.net/) outlining the issue? If you are seeing that a constructor is never being run, I suspect it's related to how you are initializing your application.

As for the difference between `this.import` and `ImportJS.unpack` - they technically both perform the same function, but have different behavior when used with the new plugins system. Plugins are kind of funky due to how they create new "instances" of ImportJS that have their own isolated packaging namepsaces. You can think of `ImportJS.unpack` being tied to the root namepsace, while `this.import` could be referring to any one of a number of namespaces (e.g. your app and its dependencies could be 1 namespace, while some other library (plugin) your import could have it's own isolated package tree). If you aren't using plugins though then no need to think about this too much

**Comment by millerthegorilla** [comment]
I'll make a jsfiddle right now, I know from stepping through the code during debugging that there is at line 33 in oops.js  OOPS.extend = function(props)  and the 'props' parameter is null (in the case of injected code).  The rest of the code passing through here is ok.  I'm virtually certain that I need to rewrite my class hierarchy, but I'd like to examine this issue so that I'm better informed for the future.

_this.import vs ImportJS.unpack_
aah, so, if I am using a library of code that my entire code base might need access to then I can use the presumably (global) static function ImportJS.unpack.   So, just to clarify, in the example import-demo.js from the zip file what is the [libs] section.  Are these libraries also global?  Are 'plugins' libraries that incorporate ImportJS in their code and have a module.export?

**Comment by millerthegorilla** [comment]
I've never used jsfiddle before, and can't get it to include importjs or oopsjs properly, but the code indicates what i am doing in essence.
https://jsfiddle.net/millerthegorilla/b5exa0c1/3/
The code in question is badly written as2 classes from back in the day, I haven't done much programming in the last 6 years so a lot has changed, promises and late binding were the latest thing when I finished!  I suspect I just need to refactor the code, but I'll wait for your response just to see if I am doing something wrong with the dependency injection.

**Comment by Cleod9** [comment]
_this.import vs ImportJS.unpack_
Yes, `ImportJS.unpack` is explicitly for getting your app's modules out into the global namespace so you can give other parts of your code base access. Though in import-demo.js, those libs are just file references for regular JS libs - so whether they create globals or not depend on the library. (e.g. you could add a url to jQuery for example, and it's the same as if you were to put script tags for jQuery before the rest of your app)

Anyway I have good news! I figured out the problem, here is an updated fiddle:

https://jsfiddle.net/7g7cqLt4/

There were a few syntax errors i had to fix up, but if you scroll to the bottom of the JS section you'll see I added a `ImportJS.compile()` before unpacking and it fixed the problem. This step is important if you're manaully unpacking stuff since unpack() doesn't resolve injected dependencies, it just returns whatever module you ask for. Anyway, the technical details for this are described in these parts of the readme:

**compile():**

> ImportJS will automatically try to compile modules when it encounters import/unpack on the fly, however is recommended that you compile them right away to avoid potential confusion.

**this.inject(callback):**

> This function accepts a callback function that is executed during the compile() step.

Perhaps I'll update the readme to make it a bit clearer what the role of compile() is. Let me know if this change works for you!

**Comment by millerthegorilla** [comment]
Ok, thanks for your help, however, I am preloading using ImportJS.preload with an entrypoint into subclass, so where is it appropriate to call ImportJS.compile() ?

``` javascript
ImportJS._settings.debug = false;
ImportJS.preload({
    baseUrl: 'scripts',
    packages: ['vine/climber.js'],
    entryPoint: 'vine.climber:new'
});
```

**Comment by Cleod9** [comment]
Oh I see, `preload()` should definitely be calling compile automatically for you in that case. I assume all of your scripts are located under `scripts/` as separate files right? Could you try this for me:

``` js
ImportJS.preload({ 
    baseUrl: 'scripts',
    packages: ['vine/climber.js'],
    autoCompile: false,
    ready: function(filesArr) {
        console.log("done, loaded files: ", filesArr);
        ImportJS.compile();
        var App = ImportJS.unpack('vine.climber');
        new App();
    },
    error: function(filesArr) {
        console.log("error on files: ", filesArr);
    }
});
```

This will manually do the compilation step and might help indicate where the problem could lie

**Comment by millerthegorilla** [comment]
Thanks, I'd more or less done that and have just run it as above.  Still no joy unfortunately.  oops.js returns an empty function, although it resolves to the correct class on inspection in the console, but the constructor is never entered.   I tried refactoring the code so that the branches are created in the climber, but the constructor of the branches is still not being called.  I tried stubbing out all the code in the branch class and storing a new branch in a variable before pushing that variable on to the branches array, but no luck, the variable is typed as a 'child' - an empty function.
I've just tried stubbing out the functions in branch and then calling branch from the preload instead of vine.climber with a console.log('hello') in the constructor of branch - it's still not being called?   I'm scratching my head - I can't think what might be happening.

**Comment by millerthegorilla** [comment]
I can't seem to extend climberbase twice, without oops returning an empty function instead of the new class.  I've uploaded the code to dropbox:
https://www.dropbox.com/sh/jie4fakvuvm6zyx/AADzvADVOUAZNDLGxCHN_xifa?dl=0
in case you want to take a look.  I'll try again tomorrow.

**Comment by Cleod9** [comment]
So I pulled your code down locally to play around with it, is there a specific part I need to change to reproduce the error? Right out of the box it does seem to be drawing something without any errors, looks like a randomized branch. (Btw the code is well organized nonetheless, so you've definitely got the overall structure correct)

**Comment by millerthegorilla** [comment]
The main branch that you can see is the climber class, as it is drawn, a check is made in the climberbase class that it extends to see if a branch should be drawn.  If it is drawn, then in the climberbase, a new branch is pushed on to the array of branches.  I moved the code around before I uploaded it to put the new branch check and branch array into the subclasses.  What it should be drawing is that main branch and then a bunch of smaller branches.  The completed animation is running on http://www.fontevraud.co.uk but it is in flash, back when I thought full flash websites were the way forward!  So I am redoing the whole site in html5, and so far it is a breeze apart from this issue.
I am guessing that the problem is that when a new branch is created, because it extends climberbase, in which the branch is late bound (injected), oops doesn't want to return a reference to the class until it is constructed, and therefore the branch constructor is never created.  There are a couple of other design patterns that I can use, but this is really a direct copy of the code from as2, so I figured it would work out of the box more or less.
What I will probably do is redesign with a factory pattern or similar, creating a third class that creates climber and branches and is called by the climber with currentPoint, when it wants to create a branch.
Many thanks for your help.

**Comment by millerthegorilla** [comment]
I tried a bunch of different permutations and it is clear that when I extend a separate class from OOPS.js whether it is in an ImportJS context or not, and whether or not it extends from the same super class, the constructor of that second class is not called.  Its probably my code, although I tried stubbing everything out and separating the two classes so that they extended from separate superclasses, but to no avail.

**Comment by Cleod9** [comment]
Oh hahaha, I figured it out :smile: 

`_contructor_` in twig.js

Should be
`_constructor_`
with an "s"

**Comment by millerthegorilla** [comment]
aah,  since I last read this, I've finished the project using standard javascript prototype overloading and object.create etc.  I've still used importJS though, its fantastic, so flexible.  I wondered if one might not be able to add an array of global variables in the preloader, that are available for all scripts in the importJS context, but then I can just as easily create a global static class and import it where I need it, at least I guess without thinking too much at this time of night!  Many thanks for your help!  (I may convert the project to oopjs and I have an html5 animation studio project that I will use it for - thanks!)

**Comment by Cleod9** [comment]
Ha, too bad we didn't realize sooner! I guess I'll close out this ticket

In any case I was wondering, are you familiar with [TypeScript](http://www.typescriptlang.org/) and/or [CreateJS](http://createjs.com/)? While I definitely encourage ImportJS when working with raw JavaScript, I think you'll find TypeScript (a superset to JS) to be a very similar experience to AS3 in terms of syntax. And CreateJS is a JS lib based on Flash's drawing API making graphical operations much more familiar. I've been using ImportJS far less than I used to since the TypeScript ecosystem basically takes care of circular dependencies in a similar manner behind the scenes. I definitely recommend it if you plan on scaling up any JS projects :)
